<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_clean</name>
   <tag></tag>
   <elementGuidId>b2e57a8d-161d-44ee-bd74-7b193f701209</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[normalize-space()=&quot;clean&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[normalize-space()=&quot;clean&quot;]</value>
   </webElementProperties>
</WebElementEntity>
